### ISSUE TITLE
symbolic 2.8.0 test failure under Octave.app 4.4.1-u1

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#168]
Symbolic pkg's tests are failing.

I suspec that this is because it needs a special Python environment which has the third-party (PyPI) sympy Python module installed, instead of just the Python standard library.

## Details

```
>> pkg install -forge symbolic
2019-10-21 01:56 octave-gui[9068] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'

2019-10-21 01:56 octave-gui[9068] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'

For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>> pkg load symbolic
>> runtests2 -pkg symbolic
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/bernoulli.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      3/14
                                                                FAIL      9
                                            (expected failure) XFAIL      2
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/chebyshevT.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      4/10
                                                                FAIL      6
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/chebyshevU.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      4/10
                                                                FAIL      6
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/coshint.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      0/3
                                                                FAIL      3
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/cosint.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      0/15
                                                                FAIL     14
                                            (expected failure) XFAIL      1
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/dilog.m Symbolic pkg v2.8.0: Traceback (most recentcall last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      0/3
                                                                FAIL      3
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/euler.m Symbolic pkg v2.8.0: Traceback (most recentcall last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      3/14
                                                                FAIL     11
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/fresnelc.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      0/3
                                                                FAIL      3
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/fresnels.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      0/3
                                                                FAIL      3
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/harmonic.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      0/2
                                                                FAIL      2
  /Users/janke/Library/Application Support/Octave.app/4.4.1/pkg/symbolic-2.8.0/@double/logint.m Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
 PASS      0/3
[... and lots more similar errors ...]
```

**Comment by apjanke** [comment]
Closing as Upstream. I think this is about how symbolic needs a non-default Python environment with sympy and other third-party packages installed, and not about how Octave.app interacts with it. That isn't something Octave.app supports doing "batteries included" for, and I don't have the time and Python/sympy familiarity to sort this out at the moment.

In the future, we'll probably need to think about how Octave.app pulls in Python environments. Or maybe not? Maybe the user can install a pip package into a per-user package repo against the system python3, and that will be sufficient?
